# TASK 1
Bat = r"""
                 _..__.          .__.._
               .^"-.._ '-(\__/)-' _..-"^.
                      '-.' oo '.-'
                         `-..-'  fsc  
"""
print(Bat)
# TASK 2
Acorn = r"""
              _
            _/-\_
         .-`-:-:-`-.
        /-:-:-:-:-:-\
        \:-:-:-:-:-:/
         |`       `|
         |         |
    jgs  `\       /'
           `-._.-'
              `
"""
print(Acorn)

# TASK 3
Anchor = r"""
                   ___
                  /   \
                 |  o  |
                  \   /
           ________) (________
          |                   |
          '------.     .------'
                  |   |
                  |   |
                  |   |
                  |   |
       /\         |   |         /\
      /_ \        /   \        / _\
        \ '.    .'     '.    .' /
         \  '--'         '--'  /
    jgs   '.                 .'
            '._           _.'
               `'-.   .-'`
                   \ /
                    `
"""
print(Anchor)

# TASk 4
Bug = r"""

 \(")/
 -( )-
 /(_)\
             tre
"""
print(Bug)

# TASK 5
Apple = r"""
        /)
   .-"".L,""-.
  ;       :.  :
  (       7:  )
   :         ;
ctr "..-"-.."
"""
print(Apple)